default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: WordingsStore_development


test:
  <<: *default
  database: WordingsStore_test

#
production:
  <<: *default
  database: WordingsStore_production
  username: WordingsStore
  password: <%= ENV['WORDINGSSTORE_DATABASE_PASSWORD'] %>
